#!/usr/bin/env bash
# make-launcher-app.sh — (re)build "~/Applications/Claude Launcher.app".
#
# The launcher is a thin app bundle whose only job is to run launch-claude.sh,
# tee its output to a log, surface a notification if anything warned, and copy
# Claude.app's icon so it looks identical in the dock. Idempotent: rebuilds the
# bundle from scratch each run. Run this once after cloning, or re-run after
# editing the template below.

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"   # .../dotfiles/claude/launch
PREP_SCRIPT="${REPO_DIR}/launch-claude.sh"

APP="${HOME}/Applications/Claude Launcher.app"
REAL_APP="/Applications/Claude.app"

chmod +x "${PREP_SCRIPT}"

echo "Building ${APP}"
rm -rf "${APP}"
mkdir -p "${APP}/Contents/MacOS" "${APP}/Contents/Resources"

# --- Contents/MacOS/launcher : the executable the bundle runs -----------------
cat > "${APP}/Contents/MacOS/launcher" <<EOF
#!/bin/bash
# Generated by make-launcher-app.sh — do not edit here; edit launch-claude.sh.
export PATH="/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin:\${PATH:-}"
PREP="${PREP_SCRIPT}"
LOG="\${HOME}/.claude/logs/launch-claude.log"
mkdir -p "\$(dirname "\${LOG}")"

ts="\$(date '+%Y-%m-%d %H:%M:%S')"
out="\$("\${PREP}" 2>&1)"
{
  echo "===== \${ts} ====="
  printf '%s\n' "\${out}"
} >> "\${LOG}"

if printf '%s' "\${out}" | grep -q 'WARN'; then
  /usr/bin/osascript -e 'display notification "Sync had warnings — see ~/.claude/logs/launch-claude.log" with title "Claude Launcher"' >/dev/null 2>&1 || true
fi
EOF
chmod +x "${APP}/Contents/MacOS/launcher"

# --- Contents/Info.plist ------------------------------------------------------
cat > "${APP}/Contents/Info.plist" <<'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key>            <string>Claude Launcher</string>
  <key>CFBundleDisplayName</key>     <string>Claude Launcher</string>
  <key>CFBundleIdentifier</key>      <string>com.diganta.claude-launcher</string>
  <key>CFBundleVersion</key>         <string>1.0</string>
  <key>CFBundleShortVersionString</key><string>1.0</string>
  <key>CFBundlePackageType</key>     <string>APPL</string>
  <key>CFBundleExecutable</key>      <string>launcher</string>
  <key>CFBundleIconFile</key>        <string>icon</string>
  <key>LSUIElement</key>             <true/>
  <key>NSHighResolutionCapable</key> <true/>
</dict>
</plist>
EOF

# --- copy Claude's icon so the dock tile looks identical -----------------------
icns="$(ls "${REAL_APP}/Contents/Resources/"*.icns 2>/dev/null | head -1 || true)"
if [[ -n "${icns}" ]]; then
  cp "${icns}" "${APP}/Contents/Resources/icon.icns"
  echo "  icon: copied from ${icns##*/}"
else
  echo "  WARN: no .icns found in ${REAL_APP}; launcher will use a generic icon"
fi

# Refresh Launch Services / icon cache so Finder & dock pick up the new bundle.
touch "${APP}"
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister \
  -f "${APP}" >/dev/null 2>&1 || true

echo "Done: ${APP}"
echo "Test it without launching the app:  ${PREP_SCRIPT} --no-open"
